name: Run Colab Notebook Daily


on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: '30 3 * * 1-5'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install papermill jupyter nbconvert

      - name: Execute Notebook
        run: |
          papermill updated_nifty_50.ipynb output.ipynb
      - name: Set up Git Authentication
        run: |
          git config --global user.email "amitvashistha1997@gmail.com"
          git config --global user.name "amitvashista"
          git config --global credential.helper store
          git remote set-url origin https://amitvashista:${{ secrets.GH_PAT2 }}@github.com/amitvashista/nifty_50.git
      
      
      - name: Push changes
        run: |
          git add -A
          git commit -m "Updated XLSX files"
          git push origin main
